DROP TABLE IF EXISTS shopping_list;
CREATE TABLE IF NOT EXISTS shopping_list(
  item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  date_added TIMESTAMP DEFAULT now(),
  checked BOOLEAN DEFAULT FALSE,
  category grocery
);

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);